#! /bin/bash
# This script constructs a single file out of all lexical entries that were manually defined, i.e.,
# all lexical entries from the files listed in the lkb/my-script configuration file execepting 
# lexicon.tdl, generated by the customization questionnaire
tr -s "\n" " " < lkb/my-script | grep -Eo "@start.*@end" |  grep -Eo "[-a-z0-9]+\.tdl" | awk '$1 !~ /^lexicon\.tdl$/' | xargs cat > my-lexicon.tdl
