name:                tools
version:             0.1.0.0
github:              "githubuser/tools"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tools#readme>

dependencies:
- base >= 4.7 && < 5
- text
- hs-conllu
- filepath
- aeson
- bytestring
- regex-tdfa
- utf8-string
- containers
- split
- directory
- regex-compat

library:
  source-dirs: src

executables:
  tools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tools

tests:
  tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tools
